User.create(username: "jenny", password: "password")
User.create(username: "jonny", password: "password")
User.create(username: "donny", password: "password")
User.create(username: "fonz", password: "password")
User.create(username: "conny", password: "password")
User.create(username: "erens", password: "password")

Sub.create(category: "cats", moderator_id: 1)
Sub.create(category: "titans", moderator_id: 1)
Sub.create(category: "titan cats", moderator_id: 2)
Sub.create(category: "sports", moderator_id: 3)

Link.create(url: "espn.com", text: "lebron lost!", title: "heat lose!", submitter_id: 1)
Link.create(url: "nsa.gov", text: "They are reading!", title: "surveillance!", submitter_id: 2)
Link.create(url: "apple.com", text: "It sure looks good!", title: "ios7", submitter_id: 4)
Link.create(url: "itunes.com", text: "Listening to some good tunes!", title: "music!", submitter_id: 5)
Link.create(url: "reuters.com", text: "I LIKE TO SHOUT!", title: "Capitals!", submitter_id: 6)
Link.create(url: "elitedaily.com", text: "millennial douchebagisms!", title: "for all of us", submitter_id: 1)
Link.create(url: "cats.com", text: "meeeowwww!", title: "rawr", submitter_id: 3)

Linksub.create(link_id: 2, sub_id: 2)
Linksub.create(link_id: 7, sub_id: 1)
Linksub.create(link_id: 1, sub_id: 4)
Linksub.create(link_id: 3, sub_id: 4)
Linksub.create(link_id: 6, sub_id: 3)
Linksub.create(link_id: 5, sub_id: 1)
Linksub.create(link_id: 2, sub_id: 1)
