User.create(username: "jenny", password: "password")
User.create(username: "jonny", password: "password")
User.create(username: "donny", password: "password")
User.create(username: "fonz", password: "password")
User.create(username: "conny", password: "password")
User.create(username: "erens", password: "password")

Sub.create(category: "cats", moderator_id: 1)
Sub.create(category: "titans", moderator_id: 1)
Sub.create(category: "titan cats", moderator_id: 2)
Sub.create(category: "sports", moderator_id: 3)

Link.create(url: "espn.com", text: "lebron lost!", title: "heat lose!", submitter_id: 1)
Link.create(url: "nsa.gov", text: "They are reading!", title: "surveillance!", submitter_id: 2)
Link.create(url: "apple.com", text: "It sure looks good!", title: "ios7", submitter_id: 4)
Link.create(url: "itunes.com", text: "Listening to some good tunes!", title: "music!", submitter_id: 5)
Link.create(url: "reuters.com", text: "I LIKE TO SHOUT!", title: "Capitals!", submitter_id: 6)
Link.create(url: "elitedaily.com", text: "millennial douchebagisms!", title: "for all of us", submitter_id: 1)
Link.create(url: "cats.com", text: "meeeowwww!", title: "rawr", submitter_id: 3)

Linksub.create(link_id: 2, sub_id: 2)
Linksub.create(link_id: 7, sub_id: 1)
Linksub.create(link_id: 1, sub_id: 4)
Linksub.create(link_id: 3, sub_id: 4)
Linksub.create(link_id: 6, sub_id: 3)
Linksub.create(link_id: 5, sub_id: 1)
Linksub.create(link_id: 2, sub_id: 1)

Comment.create(title: "haha!", text: "I thought so!", commenter_id: 1, parent_comment_id: nil, link_id: 1)
Comment.create(title: "You said it!", text: "100% agree!", commenter_id: 2, parent_comment_id: 1, link_id: 1)
Comment.create(title: "douchebags", text: "Very strong words dont uthink?", commenter_id: 4, parent_comment_id: nil, link_id: 6)
Comment.create(title: "What songs", text: "SEnd to me!", commenter_id: 1, parent_comment_id: nil, link_id: 4)

UserVote.create(voter_id: 1, link_id: 1, vote_value: "up")
UserVote.create(voter_id: 1, link_id: 2, vote_value: "down")
UserVote.create(voter_id: 1, link_id: 4, vote_value: "up")
UserVote.create(voter_id: 2, link_id: 1, vote_value: "up")
UserVote.create(voter_id: 3, link_id: 1, vote_value: "up")
UserVote.create(voter_id: 4, link_id: 1, vote_value: "up")
UserVote.create(voter_id: 3, link_id: 2, vote_value: "down")